runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.html)

...

# Site root.
- url: /
  static_files: dist/<app-name>/index.html
  upload: dist/<app-name>/index.html

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/<app-name>/index.html
  upload: dist/<app-name>/index.html

skip_files:
  - ^(?!dist)