runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.html)

skip_files:
  - ^(?!dist)