runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyDkHYmlYRXbcB5HrEauCadeXAxTvy-5LLA

handlers:

- url: /(.*\.css)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/<app-name>/\1
  upload: dist/<app-name>/(.*\.html)

- url: /
  static_files: dist/<app-name>/index.html
  upload: dist/<app-name>/index.html

- url: /.*
  static_files: dist/<app-name>/index.html
  upload: dist/<app-name>/index.html

skip_files:
  - ^(?!dist)