runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyDkHYmlYRXbcB5HrEauCadeXAxTvy-5LLA

handlers:

  - url: /
    static_files: dist/<app-name>/index.html
    upload: dist/<app-name>/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE