runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyDkHYmlYRXbcB5HrEauCadeXAxTvy-5LLA

handlers:

- url: /(.*\.css)
  static_files: dist/angular-tour-of-heroes/\1
  upload: dist/angular-tour-of-heroes/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/angular-tour-of-heroes/\1
  upload: dist/angular-tour-of-heroes/(.*\.html)

- url: /
  static_files: dist/angular-tour-of-heroes/index.html
  upload: dist/angular-tour-of-heroes/*

- url: /.*
  upload: dist/angular-tour-of-heroes/*

skip_files:
  - ^(?!dist)